config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :itineraries do
    resources :reviews
  end

  resources :downloads, only: [:create, :show]

  resources :pages, only: [:new, :create,:show, :edit, :update,:destroy]
  post 'pages/results'=> 'pages#results'

  get ':name', :to => "pages#show"

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
  before_save {self.trip_in_days = trip_duration.converted_to_days}
  before_save {self.country = country.downcase}
  validates :user_id, presence: true
  validates :country, presence: true
  validates :locations, presence: true
  validates :trip_duration, presence: true
  validates :budget, presence: true, numericality: { only_integer: true}
  has_attached_file :document,
                    :storage =>:s3,
                    :s3_host_name => 's3-us-west-2.amazonaws.com',
                    :s3_credentials => File.new('config/s3_info.yml'),
                    :s3_permissions => :public_read,
                    styles: { medium: ["165x210#", :jpg]}
  validates_attachment_presence :document
  validates_attachment_content_type :document, content_type: ['application/pdf']
  after_initialize :set_cost

  #Geocode by country
  geocoded_by :country
  after_validation :geocode

  has_many :reviews

  has_many :downloads, foreign_key: "downloaded_id"
  has_many :downloaders, through: :downloads

  private

  def set_cost
    self.credit_cost ||= 1
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @search = params[:query][:search]
    duration = params[:query][:duration].converted_to_days
    budget = params[:query][:budget]
    @itineraries ||= Itinerary.where('country = ? AND trip_in_days <= ? AND budget <= ?', @search, duration, budget)
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @user = User.find_by(params[@itinerary.user_id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PreviewPDF.new(@itinerary)
        send_data pdf.render, filename: "#{@itinerary.document_file_name}_preview.pdf",
        type: 'application/pdf', disposition: 'inline'
      end
    end

  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = current_user.itineraries.build(itinerary_params)
    if @itinerary.save
      # render the page with the users itineraries
      current_user.upload_credits
      flash[:success] = 'Your itinerary has been added!'
      redirect_to current_user
    else
      render '_new'
    end
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:country, :locations, :trip_duration,
    :budget, :document)
  end

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
#require "open-uri"
#  def preview(itinerary)
#    file_name = File.open("public/#{itinerary.document_file_name}","rb")
#    page = 1

#    itinerary.previewer(file_name, page)

#  end

#def previewer(itinerary)
#  file_name = File.open("public/#{itinerary.document_file_name}")
#  file = StringIO.new(file_name)
#  reader = PDF::Reader.new(file_name)
#  preview = reader.page(1)

#  puts preview.text

#end
def user_is_reviewer?(review_id)
  if logged_in?
  current_user||= User.find(params[:id])
  review = Review.find(review_id)
  current_user.id == review.user_id
  end
end

def avg_review(itin)
  if itin.reviews.blank?
    0
  else
    itin.reviews.average(:rating).round(2)
  end
end


end

app/views/itineraries/_download.html.erb
<%= form_for(current_user.downloads.build, url: {controller: 'downloads', action: 'create'}) do |f| %>
<div><%= hidden_field_tag :downloaded_id, @itinerary.id %></div>
<%= f.submit "Download", class: "btn btn-primary" %>
<% end %>

app/views/itineraries/_form.html.erb
<%= form_for(@itinerary, html: { multipart: true } ) do |f| %>
<%= render "shared/upload_errors" %>

<%= f.label :country %>
<%= f.text_field :country, style: "margin-bottom:5px;" %>

<%= f.label "Places You Went To" %>
<%= f.text_field :locations, style: "margin-bottom:5px;"  %>

<%= f.label :trip_duration %>
<%= f.text_field :trip_duration, style: "margin-bottom:5px;"  %>

<%= f.label :budget %>
<%= f.text_field :budget, style: "margin-bottom:5px;"  %>
<span class="document" >
<%= f.label :itinerary%>
<%= f.file_field :document, accept: 'application/pdf', style: "margin-bottom:5px;"  %>
</span>
<%= f.submit "Add Itinerary", class: "btn btn-primary" %>

<% end %>

app/views/itineraries/_itinerary_view.html.erb
<%= pdfjs_viewer pdf_url: "#{@itinerary.document}", style: :full %>

app/views/itineraries/_new.html.erb
<% provide(:title, "Upload A New Itinerary")%>
<div class = "upload-container">
  <h1>Upload A New Itinerary</h1>
  <div class="row">
    <div class=" col-md-4 col-md-offset-4">
      <%= render "itineraries/form" %>
    </div>
  </div>
</div>

app/views/itineraries/index.html.erb
<h1> <%= @search.titleize%> </h1>
<div class = "row">
<% if @itineraries.blank? %>
<div class= "jumbotron">

<img src="https://d13yacurqjgara.cloudfront.net/users/502620/screenshots/1523145/fighter_plane_line.gif"
style= "width:400px;height:300px">
<br>
 <h3> Sorry, we have no itineraries for that country. </h3>

</div>
<% else %>
<% @itineraries.each do |itin| %>
<div class = "col-md-2">
<div class = "itin-preview-container">

<%= link_to image_tag(itin.document.url(:medium)), itin %>
<div class= "itinerary-stats">
<ul>
  <li> Cities:  <%= itin.locations %> </li>
  <li> Duration: <%= itin.trip_duration %> </li>
  <li> Budget: $ <%= itin.budget %> </li>
</ul>

</div>
</div>
</div>


<% end %>
<% end %>

</div>

app/views/itineraries/new.js.erb
$("#upload-modal").html("<%= escape_javascript(render 'new')%>");
$("#upload-modal").modal("show")

app/views/itineraries/show.html.erb
<% provide(:title," #{@itinerary.country} Guide")%>
<div class="row">
  <div class="col-md-8">
    <h1> <%= @itinerary.user.name %>'s <%= @itinerary.country%> Guide </h1>
    <div class = "preview-container">
      <div class = "preview-msg">
        <h2>This is a preview. Click download to get the full version!</h2>
      </div>

      <iframe class="itinerary-viewer" src= "<%=  pdfjs.full_path(file: "#{itinerary_path(@itinerary, format: :pdf)}") %>"
      frameborder="0">
      </iframe>
    </div>


    <div class = "review-container">
      <h2>What Travelers Thought</h2>

      <% if @itinerary.reviews.count > 0 %>
      <%= link_to "Add Your Review", new_itinerary_review_path(@itinerary, @review) %>
        <% @itinerary.reviews.each do |review| %>
        <div class = "reviews">
          <div class = "star-rating" data-score= <%= review.rating %> ></div>
          <p>
            <%= review.comment %>
          </p>

          <% if  user_is_reviewer?(review) %>
            <%= link_to "Delete", itinerary_review_path(@itinerary, review), method: 'delete', data: {confirm: "Are you sure you want to delete?"} %>
          <% end %>
          </div>
        <% end %>
      <% else %>
      <h2>There are no reviews for this itinerary. Add one now.</h2>
      <%= link_to "Add A Review", new_itinerary_review_path(@itinerary, @review),
       class: "btn-sm btn-primary", id: "review-button" %>

      <% end %>
    </div>
  </div>

  <div class= "col-md-4">
    <section>
      <h2><%= @itinerary.user.name %></h2>

      <%= render 'users/stats' %>
      <h3>Duration</h3>
      <p><%= @itinerary.trip_duration%></p>

      <h3>Budget</h3>
      <p><%= @itinerary.budget%></p>

      <h3>Cities Visited</h3>
      <p><%= @itinerary.locations%></p>

      <div class = 'star-rating' data-score = <%= avg_review(@itinerary) %> ></div>
      <p>
        <%= link_to "See All Reviews", itinerary_reviews_path(@itinerary, @review) %>
      </p>

      <% if logged_in? && current_user != @itinerary.user %>
      <% unless current_user.downloaded?(@itinerary) %>
        <%= render 'download' %>
      <% end %>
      <% else %>
      <p>
        Users need to be logged in to download this.
      </p>
      <% end %>
    </section>
  </div>

</div>


<script>
$('.star-rating').raty({
  path: '/assets/',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>