config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :itineraries do
    resources :reviews
  end

  resources :downloads, only: [:create, :show]

  resources :pages, only: [:new, :create,:show, :edit, :update,:destroy]
  post 'pages/results'=> 'pages#results'

  get ':name', :to => "pages#show"

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

end

app/views/layouts/_flash_messages.html.erb
<ul>
  <% flash.each do |message_type, message| %>
   <div class= "alert alert-<%= message_type %>"><li><%= message %></li></div>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Travel Forward", root_path , id: "logo"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li  id = "upload-container"><%= button_to "Upload+", new_itinerary_path, method: 'get', remote: true, class: "btn btn-md btn-primary", id: "upload-button" %></li>
        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>

  </div>



</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= render 'layouts/flash_messages' if !flash[:search] %>
<%= yield %>
<div id = "upload-modal" class = "modal fade"></div>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
<%= render 'layouts/flash_messages' if !flash[:search] %>
<%= yield %>
<div id = "upload-modal" class = "modal fade"></div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>